debug

diff --git a/.github/workflows/build-package-release.yml b/.github/workflows/build-package-release.yml
--- a/.github/workflows/build-package-release.yml
+++ b/.github/workflows/build-package-release.yml
@@ -1,5 +1,8 @@
 name: Build and Release Electron App
 
+permissions:
+  contents: write
+
 on:
   push:
     branches: [main]
@@ -47,35 +50,38 @@ jobs:
           name: ${{ matrix.artifact-name }}
           path: dist/executables/dFusion DLP miner Setup 0.1.0.exe
 
-  create-release:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      # - name: Download all artifacts
-      #   uses: actions/download-artifact@v4
-      #   with:
-      #     path: artifacts/
+      - name: debug files / directories
+        run: pwd && ls-la && ls -la dist/executables/ || echo "Directory not found"
 
-      - name: Create Release and Upload Assets
-        uses: softprops/action-gh-release@v2
-        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ github.ref_name }}
-          name: Release ${{ github.ref_name }}
-          body: |
-            Changes in this Release:
-            - Latest miner build
-          draft: false
-          prerelease: false
-          files: ./dist/executables/dFusion DLP miner Setup 0.1.0.exe
+  # create-release:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # - name: Download all artifacts
+  #     #   uses: actions/download-artifact@v4
+  #     #   with:
+  #     #     path: artifacts/
 
-      - name: Log build result
-        if: always()
-        run: |
-          if [ ${{ job.status }} == "success" ]; then
-            echo "Build and release completed successfully"
-          else
-            echo "Build and release failed"
-          fi
+  #     - name: Create Release and Upload Assets
+  #       uses: softprops/action-gh-release@v2
+  #       # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         tag_name: ${{ github.ref_name }}
+  #         name: Release ${{ github.ref_name }}
+  #         body: |
+  #           Changes in this Release:
+  #           - Latest miner build
+  #         draft: false
+  #         prerelease: false
+  #         files: ./dist/executables/dFusion DLP miner Setup 0.1.0.exe
+
+  #     - name: Log build result
+  #       if: always()
+  #       run: |
+  #         if [ ${{ job.status }} == "success" ]; then
+  #           echo "Build and release completed successfully"
+  #         else
+  #           echo "Build and release failed"
+  #         fi
